sudo: false

os:
  # FIXME:
  # - linux
  - osx

osx_image: xcode11.3

env:
  global:
  - HOMEBREW_NO_AUTO_UPDATE=1
  matrix:
  - FISH_VERSION="--HEAD"
  - FISH_VERSION="" # 3.1.0

language: c

install:
  - brew install fish $FISH_VERSION
  - brew install chruby
  - fish --version

before_script:
  - __rvm_unload
  - sudo rm -rf ~/.rvm
  - make test/opt/rubies
  - ls -lah /Users/travis/build/JeanMertz/chruby-fish/test/opt/rubies/

script: make test
